apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-deployment1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-deployment1
  template:
    metadata:
      labels:
        app: static-deployment1
    spec:
      containers:
        - name: static-nfs-container1
          image: nginx
          volumeMounts:
            - name: static-nfs-volume
              mountPath: "/var/www/html"
      volumes:
        - name: static-nfs-volume
          persistentVolumeClaim: 
            claimName: task-pv-claim
